"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { createClient } from "@/lib/supabase/client";
import { encrypt, decrypt } from "@/lib/utils/encryption";
import { useLocationStore } from "@/stores";
import { Analytics } from "@/lib/analytics/novus";
import { reverseGeocode } from "@/lib/utils";
import type { JournalEntry } from "@/lib/types";

const SEVERITY_LABELS = ["", "Minor discomfort", "Uncomfortable", "Distressing", "Frightening", "Traumatic"];
const SEVERITY_COLORS = ["", "text-night-400", "text-warn-DEFAULT", "text-orange-400", "text-danger-DEFAULT", "text-danger-DEFAULT"];
const TAGS = ["Harassment", "Followed", "Unsafe area", "Verbal abuse", "Physical", "Online", "Workplace", "Transport"];

type View = "list" | "new" | "detail";

export default function JournalPage() {
  const [view, setView] = useState<View>("list");
  const [entries, setEntries] = useState<JournalEntry[]>([]);
  const [selected, setSelected] = useState<JournalEntry | null>(null);
  const [decryptedContent, setDecryptedContent] = useState("");
  const [isLoading, setIsLoading] = useState(true);

  // New entry form
  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");
  const [severity, setSeverity] = useState(3);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [isSaving, setIsSaving] = useState(false);
  const [attachLocation, setAttachLocation] = useState(true);

  const supabase = createClient();
  const { latitude, longitude } = useLocationStore();

  useEffect(() => { loadEntries(); }, []);

  const loadEntries = async () => {
    setIsLoading(true);
    const { data } = await supabase
      .from("journal_entries")
      .select("id, title, severity, tags, created_at, latitude, longitude, address")
      .order("created_at", { ascending: false });
    setEntries((data as any[]) ?? []);
    setIsLoading(false);
  };

  const saveEntry = async () => {
    if (!title.trim() || !content.trim()) return;
    setIsSaving(true);

    let address: string | undefined;
    if (attachLocation && latitude && longitude) {
      address = await reverseGeocode(latitude, longitude);
    }

    const { error } = await supabase.from("journal_entries").insert({
      title,
      content_encrypted: encrypt(content),
      severity,
      tags: selectedTags,
      latitude: attachLocation ? latitude : null,
      longitude: attachLocation ? longitude : null,
      address,
    });

    if (!error) {
      setTitle(""); setContent(""); setSeverity(3); setSelectedTags([]);
      await loadEntries();
      setView("list");
    Analytics.journalEntryCreated(severity, selectedTags.length > 0);
    }
    setIsSaving(false);
  };

  const openEntry = async (entry: JournalEntry) => {
    const { data } = await supabase
      .from("journal_entries")
      .select("*")
      .eq("id", entry.id)
      .single();
    if (data) {
      setSelected(data);
      try { setDecryptedContent(decrypt(data.content_encrypted)); }
      catch { setDecryptedContent("[Unable to decrypt — wrong device]"); }
      setView("detail");
    }
  };

  const exportPDF = async () => {
    if (!selected || !decryptedContent) return;
    // Simple text export for now — in production use jsPDF
    const content = `ShieldHer Incident Report\n${"=".repeat(40)}\n\nTitle: ${selected.title}\nDate: ${new Date(selected.created_at).toLocaleString()}\nSeverity: ${SEVERITY_LABELS[selected.severity]}\nLocation: ${selected.address ?? "Not recorded"}\nTags: ${selected.tags.join(", ")}\n\n${"=".repeat(40)}\n\n${decryptedContent}\n\n${"=".repeat(40)}\nGenerated by ShieldHer — Confidential`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = `incident-${selected.id.slice(0,8)}.txt`; a.click();
  };

  return (
    <div className="min-h-dvh bg-night-950 flex flex-col">
      {/* Header */}
      <div className="pt-safe px-5 pt-5 pb-4 border-b border-white/5 flex items-center gap-3">
        {view !== "list" && (
          <button onClick={() => setView("list")} className="text-night-400 mr-1">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none"><path d="M19 12H5m7-7l-7 7 7 7" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>
          </button>
        )}
        <h1 className="font-display font-bold text-white text-xl flex-1">
          {view === "list" ? "My Journal" : view === "new" ? "New Entry" : "Entry"}
        </h1>
        {view === "list" && (
          <button
            onClick={() => setView("new")}
            className="w-9 h-9 rounded-full bg-shield-500 flex items-center justify-center"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none"><path d="M12 5v14m-7-7h14" stroke="white" strokeWidth="2" strokeLinecap="round"/></svg>
          </button>
        )}
        {view === "detail" && (
          <button onClick={exportPDF} className="text-night-400 text-sm">Export</button>
        )}
      </div>

      <div className="flex-1 px-5 py-4 overflow-y-auto scrollbar-hidden">
        <AnimatePresence mode="wait">

          {/* LIST VIEW */}
          {view === "list" && (
            <motion.div key="list" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
              {isLoading ? (
                <div className="text-center py-20 text-night-500">Loading...</div>
              ) : entries.length === 0 ? (
                <div className="text-center py-20">
                  <div className="text-5xl mb-4">📔</div>
                  <p className="text-night-400">Your journal is private and encrypted.</p>
                  <p className="text-night-500 text-sm mt-1">Only you can read these entries.</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {entries.map((entry) => (
                    <motion.button
                      key={entry.id}
                      onClick={() => openEntry(entry)}
                      className="w-full text-left bg-night-800 border border-white/5 rounded-2xl p-4 hover:border-shield-500/20 transition-colors"
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                    >
                      <div className="flex items-start justify-between gap-2 mb-2">
                        <h3 className="text-white font-medium text-sm line-clamp-1">{entry.title}</h3>
                        <span className={`text-xs font-semibold flex-shrink-0 ${SEVERITY_COLORS[entry.severity]}`}>
                          {"●".repeat(entry.severity)}
                        </span>
                      </div>
                      <div className="flex items-center gap-3 text-xs text-night-500">
                        <span>{new Date(entry.created_at).toLocaleDateString()}</span>
                        {entry.address && <span className="truncate">📍 {entry.address.split(",")[0]}</span>}
                      </div>
                      {entry.tags?.length > 0 && (
                        <div className="flex flex-wrap gap-1 mt-2">
                          {entry.tags.map((tag) => (
                            <span key={tag} className="text-xs px-2 py-0.5 rounded-full bg-night-700 text-night-400">{tag}</span>
                          ))}
                        </div>
                      )}
                    </motion.button>
                  ))}
                </div>
              )}
            </motion.div>
          )}

          {/* NEW ENTRY */}
          {view === "new" && (
            <motion.div key="new" initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }} className="space-y-5">
              <div>
                <p className="text-night-400 text-xs uppercase tracking-widest mb-2">Entry title</p>
                <input className="input-dark" placeholder="What happened..." value={title} onChange={(e) => setTitle(e.target.value)} />
              </div>

              <div>
                <p className="text-night-400 text-xs uppercase tracking-widest mb-2">Description (encrypted)</p>
                <textarea
                  className="input-dark min-h-[160px] resize-none"
                  placeholder="Write as much or as little as you want. This is fully encrypted — only you can read it."
                  value={content}
                  onChange={(e) => setContent(e.target.value)}
                />
                <p className="text-night-600 text-xs mt-1">🔒 AES-256 encrypted. Not readable by anyone else.</p>
              </div>

              <div>
                <div className="flex justify-between mb-2">
                  <p className="text-night-400 text-xs uppercase tracking-widest">Severity</p>
                  <span className={`text-xs font-semibold ${SEVERITY_COLORS[severity]}`}>{SEVERITY_LABELS[severity]}</span>
                </div>
                <div className="flex gap-2">
                  {[1, 2, 3, 4, 5].map((s) => (
                    <button
                      key={s}
                      onClick={() => setSeverity(s)}
                      className={`flex-1 h-8 rounded-lg transition-all ${s <= severity ? SEVERITY_COLORS[severity].replace("text-", "bg-").replace("-DEFAULT", "-400/30") + " border border-current/30" : "bg-night-800 border border-white/5"}`}
                    />
                  ))}
                </div>
              </div>

              <div>
                <p className="text-night-400 text-xs uppercase tracking-widest mb-2">Tags</p>
                <div className="flex flex-wrap gap-2">
                  {TAGS.map((tag) => (
                    <button
                      key={tag}
                      onClick={() => setSelectedTags((prev) => prev.includes(tag) ? prev.filter((t) => t !== tag) : [...prev, tag])}
                      className={`px-3 py-1.5 rounded-full text-xs transition-all ${selectedTags.includes(tag) ? "bg-shield-500 text-white" : "bg-night-800 text-night-400 border border-white/10"}`}
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex items-center gap-3 bg-night-800 rounded-xl px-4 py-3 border border-white/5">
                <div className="flex-1">
                  <p className="text-white text-sm font-medium">Attach location</p>
                  <p className="text-night-500 text-xs">{latitude ? `${latitude.toFixed(4)}, ${longitude?.toFixed(4)}` : "No GPS signal"}</p>
                </div>
                <button
                  onClick={() => setAttachLocation(!attachLocation)}
                  className={`w-12 h-6 rounded-full transition-colors ${attachLocation ? "bg-shield-500" : "bg-night-700"}`}
                >
                  <div className={`w-5 h-5 rounded-full bg-white mx-0.5 transition-transform ${attachLocation ? "translate-x-6" : ""}`} />
                </button>
              </div>

              <button onClick={saveEntry} disabled={!title || !content || isSaving} className="btn-primary w-full disabled:opacity-40">
                {isSaving ? "Saving..." : "Save Entry"}
              </button>
            </motion.div>
          )}

          {/* DETAIL VIEW */}
          {view === "detail" && selected && (
            <motion.div key="detail" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-4">
              <div>
                <h2 className="font-display font-bold text-xl text-white mb-1">{selected.title}</h2>
                <div className="flex items-center gap-3 text-xs text-night-500">
                  <span>{new Date(selected.created_at).toLocaleString()}</span>
                  <span className={SEVERITY_COLORS[selected.severity]}>{SEVERITY_LABELS[selected.severity]}</span>
                </div>
              </div>
              {selected.address && (
                <div className="bg-night-800 rounded-xl px-4 py-3 flex items-center gap-2 border border-white/5">
                  <span className="text-sm">📍</span>
                  <p className="text-night-300 text-sm">{selected.address}</p>
                </div>
              )}
              {selected.tags?.length > 0 && (
                <div className="flex flex-wrap gap-1">
                  {selected.tags.map((tag) => (
                    <span key={tag} className="text-xs px-2 py-1 rounded-full bg-night-800 text-night-400 border border-white/5">{tag}</span>
                  ))}
                </div>
              )}
              <div className="bg-night-800 rounded-2xl p-4 border border-white/5">
                <p className="text-night-200 text-sm leading-relaxed whitespace-pre-wrap">{decryptedContent}</p>
              </div>
              <div className="text-center">
                <p className="text-night-600 text-xs">🔒 End-to-end encrypted. Export for legal use.</p>
              </div>
            </motion.div>
          )}

        </AnimatePresence>
      </div>
    </div>
  );
}
